spring:
  datasource:
    url: jdbc:postgresql://database-1.cfwis2ku6pb3.sa-east-1.rds.amazonaws.com:5432/fitLifeBuddy
    username: postgres
    password: joshue123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
logging:
  level:
    root: WARN
    com.fitLifeBuddy: DEBUG
